// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Ja244Hufxkdx-rDd3PAKHz_xuqP6JEg',
    appId: '1:349062106097:android:1835e7f83e0970410dd250',
    messagingSenderId: '349062106097',
    projectId: 'macro-dreamer-348416',
    storageBucket: 'macro-dreamer-348416.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbOeMwC9G6JpEAAKoWO3fvDo0GUSdeXE',
    appId: '1:349062106097:ios:a0aced84c882bfe90dd250',
    messagingSenderId: '349062106097',
    projectId: 'macro-dreamer-348416',
    storageBucket: 'macro-dreamer-348416.appspot.com',
    iosClientId: '349062106097-om4227gsokropmiph2n5p0hop328g68d.apps.googleusercontent.com',
    iosBundleId: 'com.example.geofencedAttendanceSystem',
  );
}
